import { NextPage } from "next";
import styles from '../styles/Home.module.css';
import { Livro } from "@/classes/modelo/Livro";
import { useEffect, useState } from "react";
import Head from "next/head";
import { Menu } from "@/components/Menu";
import { LinhaLivro } from "@/components/LinhaLivro";

const LivroLista: NextPage = () => {
  const [livros, setLivros] = useState<Array<Livro>>([]);
  const [carregado, setCarregado] = useState<boolean>();
  
  const baseURL = "http://localhost:3000/api/livros";


  const obterLivros = async () => {
    try {
      const response = await fetch(baseURL);
      const data = await response.json();
      return data;
    } catch (err) {
      console.log('Erro ao obter os dados:', err);
    }
  };

  const excluirLivro = async (codigo: number) => {
    try {
      const response = await fetch(`${baseURL}/${codigo}`, {
        method: 'DELETE'
      });
      const data = await response.json();
      return data.ok;
    } catch (err) {
      console.log('Erro ao excluir o livro:', err);
    }
  };

  const excluir = (codigo: number) => {
    excluirLivro(codigo);
    setCarregado(false);
  }

  useEffect(() => {
    obterLivros().then(livros => {
      setLivros(livros);
      setCarregado(true);
    });
  }, [carregado])

  return (
    <div className={`${styles.container}`}>
      <Head>
        <title>Loja Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <main className="p-4">
      <h1>Catálogo de Livros</h1>
      <table className="table">
        <thead className="table-dark">
          <tr>
            <th>Título</th>
            <th>Resumo</th>
            <th>Editora</th>
            <th>Autor(es)</th>
          </tr>
        </thead>
        <tbody>
          {livros.map(livro => (
            <LinhaLivro key={livro.codigo} livro={livro} excluir={excluir} />
          ))}
        </tbody>
      </table>
    </main>
    </div>
  );
};

export default LivroLista;